### ISSUE TITLE
[SP2] Finalize email summary content

### ISSUE THREAD

**Issue by gomgam** [gomgam/fullstact-react#1]
Prototype for content to use for first version that we'll launch with: https://simplesat-prototype.herokuapp.com/email/email-summary-v1

![image](https://user-images.githubusercontent.com/2689853/56453691-6eeca400-6370-11e9-81ec-8114c6ae5f51.png)

Notes about content:

- Need to finalize the "New from Simplesat" headline and text
- I think there are some unused tables that could be cleaned up around the button area

Also to do:

- CSAT score should have a `%` symbol, like on the insights page
- Surveys with NPS as primary metric should display `Net Promoter Score` instead of `Satisfaction` (and no % after score)
- In our first tests the score calculation wasn't correct, for example:

![image](https://user-images.githubusercontent.com/2689853/56453753-f0443680-6370-11e9-94cd-b31a62b678fc.png)

#### Task
- [ ] Update email UI
- [ ] Add new from Simplsat text
- [ ] Change NPS to show `Net promoter score` instead of Satisfaction
- [ ] Send data to Sendgrid template and use Sendgrid condition
- [ ] Condition for some content regarding to metric:
   - [ ] Option 1: Use Sendgrid `handle bar` to create a condition for `if - else`
   - [ ] Option 2: Use python code to decide what to send to sendgrid
